# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: v1 loop task bot

on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.4'
      - name: Download v1 bot script
        run: |
          wget https://github.com/waifu-project/movie/raw/dev/script/ckbot/go.mod
          wget https://github.com/waifu-project/movie/raw/dev/script/ckbot/go.sum
          wget https://github.com/waifu-project/movie/raw/dev/script/ckbot/main.go
          go run main.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: yoyo.json